### ISSUE TITLE
GatingSet2GatingML for CyTOF GatingSets?

### ISSUE THREAD

**Issue by laderast** [RGLab/flowIncubator#26]
Hi,

I am working with CyTOF files and I'm trying to get the GatingSet2GatingML function working for my GatingSets.

The main stumbling block seems to be that the code assumes there is a compensation matrix, but there isn't one for CyTOF. Is there a way to dummy up a compensation matrix, or modify the functionality to get it to work?

Thanks,
Ted

**Comment by mikejiang** [comment]
This function has been deprecated by `GatingSet2cytobank` and `GatingSet2flowJo`.  See https://github.com/RGLab/CytoML.  
This issue should have been resolved. If not, please recreate the issue there instead.
Thanks.
